wowsTemplates = {
  # Verbesserungen Slot 1
  "Main Armaments Modification 1": "Hauptbewaffnungs-Modifikation 1",
  "Air Groups Modification 1": "Luftgruppen-Modifikation 1",
  "Auxiliary Armaments Modification 1": "Hilfsbewaffnungs-Modifikation 1",
  "Magazine Modification 1": "Magazinmodifikation 1",
  "Aiming Systems Modification 0": "Zielsystem-Modifikation 0",
  "Sonar Modification 1": "Sonar-Modifikation 1",
# Verbesserungen Slot 2
  "Damage Control System Modification 1": "Schadensbegrenzungs- system-Modifikation 1",
  "Engine Room Protection": "Schutzsystem für Manövrierbarkeit",
  "Aircraft Engines Modification 1": "Flugzeugmotor-Modifikation 1",
# Verbesserungen Slot 3
  "Main Battery Modification 2": "Hauptbatterie-Modifikation 2",
  "Secondary Battery Modification 1": "Sekundärbatterie-Modifikation 1",
  "AA Guns Modification 1": "Fla-Bewaffnungs-Modifikation 1",
  "Aiming Systems Modification 1": "Zielsystem-Modifikation 1",
  "Artillery Plotting Room Modification 1": "Artillerieplotterraum-Modifikation 1",
  "Torpedo Tubes Modification 1": "Torpedowerfer-Modifikation 1",
  "Torpedo Bombers Modification 1": "Torpedobomber-Modifikation 1",
  "Attack Aircraft Modification 1": "Schlachtflugzeug-Modifikation 1",
  "Aerial Torpedoes Modification 1": "Flugzeugtorpedo-Modifikation 1",
  "Dive Capacity Modification 1": "Tauchkapazität-Modifikation 1",
  "Skip Bomber Modification 1": "Springbomber-Modifikation 1",
  "Sonar Modification 2": "Sonar-Modifikation 2",
# Verbesserungen Slot 4
  "Damage Control System Modification 2": "Schadensbegrenzungs- system-Modifikation 2",
  "Propulsion Modification 1": "Antriebs-Modifikation 1",
  "Steering Gears Modification 1": "Steuergetriebe-Modifikation 1",
  "Attack Aircraft Modification 2": "Schlachtflugzeug-Modifikation 2",
  "Torpedo Bombers Modification 2": "Torpedobomber-Modifikation 2",
  "Bombers Modification 2": "Bomber-Modifikation 2",
  "Depth Charges Modification 1": "Wasserbomben-Modifikation 1",
  "Skip Bomber Modification 2": "Springbomber-Modifikation 2",
  "Airstrike Modification 1": "Luftschlag-Modifikation 1",
  "Submarine Steering Gears Modification 2": "U-Boot-Steuergetriebe-Modifikation 2",
# Verbesserungen Slot 5
  "Flight Control Modification 1": "Flugüberwachungs-Modifikation 1",
  "Torpedo Lookout System": "Torpedo-Überwachungssystem",
  "Concealment System Modification 1": "Tarnsystem-Modifikation 1",
  "Steering Gears Modification 2": "Steuergetriebe-Modifikation 2",
  "Ship Consumables Modification 1": "Schiffsverbrauchsmaterial-Modifikation 1",
  "Squadron Consumables Modification 1": "Staffelverbrauchsmaterial-Modifikation 1",
  "Submarine Steering Gears Modification 3": "U-Boot-Steuergetriebe-Modifikation 3",
# Verbesserungen Slot 6
  "Main Battery Modification 3": "Hauptbatterie-Modifikation 3",
  "Torpedo Tubes Modification 2": "Torpedowerfer-Modifikation 2",
  "Gun Fire Control System Modification 2": "Feuerleitanlagen-Modifikation 2",
  "Artillery Plotting Room Modification 2": "Artillerieplotterraum-Modifikation 2",
  "Flight Control Modification 2": "Flugüberwachungs-Modifikation 2",
  "Air Groups Modification 2": "Luftgruppen-Modifikation 2",
  "Auxiliary Armaments Modification 2": "Hilfsbewaffnungs-Modifikation 2",
  "Dive Capacity Modification 2": "Tauchkapazität-Modifikation 2",
# Verbesserungen Slot 7
  "Damage Control Party Modification 1": "Schadensbegrenzungs- team-Modifikation 1",
  "Spotting Aircraft Modification 1": "Aufklärungsflugzeug-Modifikation 1",
  "Engine Boost Modification 1": "Motorboost-Modifikation 1",
  "Defensive AA Fire Modification 1": "Defensives-Fla-Feuer-Modifikation 1",
  "Hydroacoustic Search Modification 1": "Hydroakustische-Suche-Modifikation 1",
  "Surveillance Radar Modification 1": "Überwachungsradar-Modifikation 1",
  "Smoke Generator Modification 1": "Nebelerzeuger-Modifikation 1",

# Verbrauchsmaterialien
  "Damage Control Party": "Schadensbegrenzungsteam",
  "Repair Party": "Reparaturmannschaft",
  "Catapult Fighter": "Jäger",
  "Spotting Aircraft": "Aufklärungsflugzeug",
  "Smoke Generator": "Nebelerzeuger",
  "Crawling Smoke Generator": "Schleichfahrt-Nebelerzeuger",
  "Exhaust Smoke Generator": "Abluft-Nebelerzeuger",
  "Engine Boost": "Motorboost",
  "Main Battery Reload Booster": "Hauptbatterie Nachladebooster",
  "Torpedo Reload Booster": "Torpedo-Nachladebeschleuniger",
  "Hydroacoustic Search": "Hydroakustische Suche",
  "Short-Range Hydro-Acoustic Search": "Hydroakustische Nahbereichssuche",
  "Defensive AA Fire": "Defensives Fla-Feuer",
  "Short-Burst Smoke Generator": "Kurzimpuls-Nebelerzeuger",
  "Surveillance Radar": "Überwachungsradar",
  "CAP Fighter": "Jäger",
  "Engine Cooling": "Motorkühlung",
  "Patrol Fighters": "Jägerpatrouille",
  "Aircraft Repair": "Reparatur",
  "Hydrophone": "Hydrofon",
  "Enhanced Rudder Gears": "Verbesserte Ruderanlage",
  "Reserve Battery Unit": "Reservebatterieeinheit",

# Sontige Templates
  "AA Sidebar Warning Insert": "",
  "":"",
  "Prem Ship Camo Insert|shiptier=10":"Prem Ship Camo Insert|shiptier=10",
  "WoWS DevBlog Link Insert":"WoWS DevBlog Link Einfügen",
}

wowsSkipTemplates = [
    "AnnoWiki*",
    "#var:ship_name",
    "Kapitänsfertigkeiten BB*",
    "Kapitänsfertigkeiten DD*",
    "Kapitänsfertigkeiten CR*",
    "Kapitänsfertigkeiten CV*",
    "Signal Flags*",
    "VideoYT*"
]
